name: global.website.name
highlighter: pygments
url:
    en: http://www.boyue.win
    zh_ch: http://www.boyue.win

include: [.htaccess]
exclude: [bin,README.md]

timezone: Asia/Shanghai

languages: ["zh_cn", "en", "zh_cn"]

description: global.website.description

excerpt_separator: ""

### 
encoding: "utf-8"
# cdn_domain: http://7xpzl2.com1.z0.glb.clouddn.com
# cdn_img_suffix: ?imageView2/2/w/800

### Disabled for now. Default is nice.
# permalink: :categories/:year-:month-:day-:title.html
# permalink: :year-:month-:day-:title.html
# The navigation to include, everything here is meant to be
# a key to find the correct page. The name and link titles are
# taken from every page itself as well as the relation to its parent.

# Each name has to be unique and the page has to have the same name 
# Check the area in -- and the name attribute for that.
# Same name, same page. URLs here are also the default built urls. 
# Custom works different.
sitenavigation:
  - name: Services
    secondarynav:
        - name: Services
        # - name: Demandware
  - name: Company
    secondarynav:
        - name: Company
        - name: Management
        - name: Team
        - name: References
        - name: Press
  - name: News
  - name: Jobs
  - name: Contact
    secondarynav:
        - name: Contact
        - name: Privacy
  - name: :External
    title: Blog
    url: https://blog.boyue.win/

